### ISSUE TITLE
theme filestructure not compatible with installer

### ISSUE THREAD

**Issue by joolswills** [RetroPie/es-theme-nbba#2]
This theme seems to have extra stuff - configs and some other images etc. It will need to be made the same structure as the other ones, or the module will need specific adjustments. perhaps we should just split it into a few repositories for each "theme", if the other bits are needed though that will need thinking about.

**Comment by joolswills** [comment]
Aha sorry @HerbFargus you fixed this with your pull request right - i mean the file structure. But perhaps we should just make three repositories/themes so no manual work is needed ? Would mean duplication of course.

**Comment by HerbFargus** [comment]
I guess we would just have to weigh out the benefit of having the alternatives- I'm fine with three, but it may just be simplest to keep the basic as a repo and refer people to the forum post for the alternate variations. I've contacted the creator of the theme and have yet to hear back from him on his feeback.

**Comment by joolswills** [comment]
ok. so let's leave it here for now then, and consider splitting up later..

**Comment by HerbFargus** [comment]
I'll repost here once I hear back.
